language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_install:
  - sudo apt install curl -y

install:
  - travis_retry composer install --no-interaction

# Testing the app
script:
  - composer run-script test
  - ./bin/ci/travis.sh